import type { Product } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => PlaceHolderImages.find((img) => img.id === id)!;

export const products: Product[] = [
  {
    id: 'prod_01',
    name: 'Midnight Oud',
    slug: 'midnight-oud',
    description: 'A deep, mysterious fragrance that combines the richness of oud with spicy and woody notes. Perfect for an unforgettable evening.',
    price: 180,
    currencyCode: 'USD',
    images: [
      getImage('prod_01_01'),
      getImage('prod_01_02'),
      getImage('prod_01_03'),
    ],
    olfactoryFamily: 'Woody',
    topNotes: ['Bergamot', 'Leather'],
    middleNotes: ['Oud', 'Rose'],
    baseNotes: ['Amber', 'Sandalwood'],
    size: '50ml',
    isTopSeller: true,
    isHazmat: true,
  },
  {
    id: 'prod_02',
    name: 'Sunkissed Jasmine',
    slug: 'sunkissed-jasmine',
    description: 'A bright, floral scent capturing the essence of a sun-drenched garden. Light, airy, and refreshingly elegant.',
    price: 120,
    currencyCode: 'USD',
    images: [
      getImage('prod_02_01'),
      getImage('prod_02_02'),
    ],
    olfactoryFamily: 'Floral',
    topNotes: ['Bergamot'],
    middleNotes: ['Jasmine'],
    baseNotes: ['Musk'],
    size: '30ml',
    isTopSeller: false,
    isHazmat: false,
  },
  {
    id: 'prod_03',
    name: 'Earthen Vetiver',
    slug: 'earthen-vetiver',
    description: 'An earthy, grounding aroma with a heart of vetiver, balanced by fresh citrus and a hint of patchouli.',
    price: 150,
    currencyCode: 'USD',
    images: [
      getImage('prod_03_01'),
      getImage('prod_03_02'),
    ],
    olfactoryFamily: 'Woody',
    topNotes: ['Bergamot'],
    middleNotes: ['Vetiver'],
    baseNotes: ['Patchouli', 'Amber'],
    size: '100ml',
    isTopSeller: true,
    isHazmat: false,
  },
  {
    id: 'prod_04',
    name: 'Spiced Amber',
    slug: 'spiced-amber',
    description: 'A warm and inviting fragrance that blends sweet amber with a medley of exotic spices. Comforting and sophisticated.',
    price: 165,
    currencyCode: 'USD',
    images: [
      getImage('prod_04_01'),
      getImage('prod_04_02'),
    ],
    olfactoryFamily: 'Oriental',
    topNotes: ['Bergamot'],
    middleNotes: ['Rose', 'Jasmine'],
    baseNotes: ['Amber', 'Vanilla', 'Patchouli'],
    size: '50ml',
    isTopSeller: false,
    isHazmat: false,
  },
  {
    id: 'prod_05',
    name: 'Rose de Mai',
    slug: 'rose-de-mai',
    description: 'A classic, romantic rose scent, capturing the delicate and fresh aroma of May roses in full bloom.',
    price: 220,
    currencyCode: 'USD',
    images: [
      getImage('prod_05_01'),
      getImage('prod_05_02'),
    ],
    olfactoryFamily: 'Floral',
    topNotes: ['Bergamot'],
    middleNotes: ['Rose'],
    baseNotes: ['Sandalwood', 'Musk'],
    size: '100ml',
    isTopSeller: true,
    isHazmat: false,
  },
  {
    id: 'prod_06',
    name: 'Coastal Drift',
    slug: 'coastal-drift',
    description: 'A fresh, aquatic fragrance that evokes a walk along the coast, with notes of sea salt and a hint of woody sage.',
    price: 110,
    currencyCode: 'USD',
    images: [
      getImage('prod_06_01'),
      getImage('prod_06_02'),
    ],
    olfactoryFamily: 'Fresh',
    topNotes: ['Bergamot'],
    middleNotes: ['Jasmine'],
    baseNotes: ['Sandalwood'],
    size: '50ml',
    isTopSeller: false,
    isHazmat: false,
  },
];

export const olfactoryFamilies = [...new Set(products.map(p => p.olfactoryFamily))];
export const allNotes = [...new Set(products.flatMap(p => [...p.topNotes, ...p.middleNotes, ...p.baseNotes]))];
export const sizes = [...new Set(products.map(p => p.size))];
